In [1]:
import pandas as pd
# Oringinal Data (RAW) "MTA_Subway_Hourly_Ridership__2020-2024_20260222.csv"
daily_ridership = pd.read_csv("MTA_Subway_Daily_Manhattan.csv")
st_cmplx_list = pd.read_csv("MTA_Subway_Daily_Manhattan_Stations.csv")

In [2]:
daily_ridership

       station_complex_id        date  ridership
0                       8  2023-01-01       8909
1                       8  2023-01-02       7475
2                       8  2023-01-03       9291
3                       8  2023-01-04      10697
4                       8  2023-01-05      10391
...                   ...         ...        ...
44128                 635  2023-12-27      18878
44129                 635  2023-12-28      20035
44130                 635  2023-12-29      23840
44131                 635  2023-12-30      15912
44132                 635  2023-12-31      11406

[44133 rows x 3 columns]

In [5]:
daily_ridership_totals = daily_ridership.groupby('date')['ridership'].sum().reset_index()

In [6]:
daily_ridership_totals

           date  ridership
0    2023-01-01    1013185
1    2023-01-02    1062726
2    2023-01-03    1734883
3    2023-01-04    1862526
4    2023-01-05    1865376
..          ...        ...
360  2023-12-27    1668616
361  2023-12-28    1769432
362  2023-12-29    1846550
363  2023-12-30    1469037
364  2023-12-31    1128420

[365 rows x 2 columns]

In [7]:
daily_ridership_totals.to_csv("~/Desktop/MTA_Subway_Daily_Manhattan_Totals.csv", index=False)

In [10]:
export_check = pd.read_csv("~/Desktop/MTA_Subway_Daily_Manhattan_Totals.csv")

In [11]:
export_check

           date  ridership
0    2023-01-01    1013185
1    2023-01-02    1062726
2    2023-01-03    1734883
3    2023-01-04    1862526
4    2023-01-05    1865376
..          ...        ...
360  2023-12-27    1668616
361  2023-12-28    1769432
362  2023-12-29    1846550
363  2023-12-30    1469037
364  2023-12-31    1128420

[365 rows x 2 columns]